### ISSUE TITLE
Help wanted: why does `make` copy 50.5 KiB after encrypt?

### ISSUE THREAD

**Issue by kmahyyg** [sunnyden/MBRLock#1]
```makefile
mbr_record:
	dd if=$(MBR_BOOT_DEVICE) of=./mbr_0 bs=512 skip=0 count=1
	dd if=./mbr_0 of=./ptable  bs=1 skip=440
	dd if=$(MBR_BOOT_DEVICE) of=./mbr_rest bs=512 skip=1 count=101
```

So sorry for disturbing.

I'm a freshman in University. My teacher once told us that the MBR is the first 512 Bytes of the disk.
Why `dd if=$(MBR_BOOT_DEVICE) of=./mbr_rest bs=512 skip=1 count=101` should be executed?

I searched in Google using the keyword `mbr 51kb`, but got nothing.

Could you please explain this or give some references to me?

Thank you a lot.

**Comment by sunnyden** [comment]
The MBR record is the first 512 bytes of the disk.
When the computer boots up it will execute instructions in the mbr. Commonly instructions in the mbr will only do some basic initialization jobs and after that the mbr will load the rest of the bootloader program on the disk because the 512 bytes mbr record is too small to store the complete bootloader program. Therefore, sectors after the first 512 bytes are commonly used by many OSs or bootloaders to store the rest of the boot loader code.

That's why the `dd if=$(MBR_BOOT_DEVICE) of=./mbr_rest bs=512 skip=1 count=101` was executed to skip the rest of the bootloader code and store the original mbr record after the bootloader program. Note that the `mbr_rest` is not part of the MBR record, actually it should be part of the bootloader program.

Should you have any other questions, feel free to ask me.

**Comment by kmahyyg** [comment]
The structure of  `product.mbr` is:

|           Label           | Size | Copied from |
|:------------------------:|:------:|:----------------:|
| MBR Encryption | \ | Compiled |
| Partition Table | 72 Bytes | Disk |
| Partial BootLoader | 50.5 KiB | Disk(After MBR) |
| MBR Decryption | \ | Compiled |
| Original MBR | 512 Bytes | \ | Disk (first sector) |

After I checked your code, one more final question:

1. What is the workflow of the whole process?

I mean: After the program loaded into `0000:7c00` , The encryption started. **And  `____?_____` (Why need bootloader code involved in here? You modified the bootloader order or did something else?)** Then Decrypted and call the original MBR function.

Thanks for your patience. 

After analyzing your program, My goal was trying to enhance it and let it run independently without specific disk(OS-related, not disk-related).

**Comment by sunnyden** [comment]
Originally, when a computer boots up, it just loads the MBR code(part of the bootloader program) to the RAM and executes it, the code will eventually load the rest of the bootloader code and jump to it, finishing the rest of booting process.  
The goal of this project is to add a password verification process before the actual MBR code is executed.  
Therefore, I replaced the original MBR code into the password verifier code, or "MBR Encryption" data in your table, in which the user's password will be verified. Once the verification process succeeded, the program will load the "decrypter" code to someplace else on the RAM (in this case is 0x8100h) and jump to it. To ensure the boot up process will be performed normally, the "decrypter" code will load the "Original MBR" back to the beginning of the RAM and jump back to `0x7C00` address on the RAM to finish the original booting process, which is simulating exactly what the BIOS did in the booting process. The only difference is the decrypter loads the MBR code from someplace else on the disk while the BIOS loads the MBR code exactly from the MBR sector. 
In fact, there is no "encrypting" or "decrypting" operation in this code. It is just a program to load the original MBR code to the RAM after a simple verification process. XD

**Comment by kmahyyg** [comment]
Thank you so much. It really helped me a lot.
